name: ourtown
version: 2.0
main: cat.nyaa.ourtown.OurTown
depend: [NyaaCore,NyaaUtils,Essentials]
authors: [cylin]
commands:
  town:
permissions:
  town.player.select:
    description: Select a spawn point
    default: true
  town.player.tp:
    description: Teleport to spawn point
    default: true
  town.admin:
    default: op
